setup.py
=> Add test package

.travis.yml, tox.ini
=> Add Twisted 15.0 in build matrix

CONTRIBUTING.rst, README.rst, docs/index.rst
Basically, "the extra information I wish I'd had when I first sat down and tried to contribute."
=> Contribution doc improvements

.travis.yml, klein/__init__.py, setup.py, tox.ini
=> Release 15.3.1 which _actually_ has py3 metadata

docs/index.rst, docs/release.rst
=> Document the release process

src/klein/resource.py, src/klein/test/test_resource.py
=> Element async render

.travis.yml, setup.py, tox.ini
=> Tox environment cleanup

src/klein/_decorators.py, src/klein/_plating.py, src/klein/app.py, src/klein/test/test_app.py, src/klein/test/test_plating.py
=> Make Plating honor 'self', and generalize how Klein deals with that.

docs/examples/handlingpost.rst
=> new: doc: @minor: Add link to Twisted docs for `twisted.web.iweb.IRequest.content`

.travis.yml, .travis/install, .travis/run, tox.ini
Borrow some script-fu from the cryptography project to install a version of pypy from the modern era.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/183)
=> Install a modern pypy.

.travis.yml, tox.ini
Rename `trial-*` environments to `coverage-*`.
Add `trial-*` environments that don't run under coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/189)
=> Add non-coverage environment

.travis.yml, tox.ini
Push to Codecov after each build, instead of once after all builds pass.
=> Push to Codecov after each build

docs/examples/await.rst, docs/examples/deferreds.rst, docs/index.rst
Add an async/await example.
Fixes #207
=> Await example

.travis.yml, tox.ini
Several PRs are [failing in the same way](https://travis-ci.org/twisted/klein/jobs/274818637#L600).
=> Codecov step is failing CI

.travis.yml, .travis/mypy, src/klein/app.py, tox.ini
This adds a mypy environment to Tox and run it in Travis.
It is not really doing much or anything at the moment, because this PR doesn't add type annotations to files, and it ignores a few existing errors, with the intention that we can start fixing those errors and adding type annotations in separate PRs.
=> Add mypy environment

.travis.yml, tox.ini
=> Add Python 3.6 and Twisted 17.1 to Travis test matrix

tox.ini
Add flake8-mutable and update most test dependencies.
This intentionally doesn't update `mypy`, which will need a bit more work, since it's catching a few new errors.
=> Add flake8-mutable and update most test dependencies

tox.ini
As per the discussion https://github.com/twisted/klein/pull/244#issuecomment-402017762 it was suggested that the code complexity value should be increased so additional logic can be appended to `KleinResource.render()` without failing CI.
=> Increase max-complexity value

docs/introduction/1-gettingstarted.rst
Mentioning this at least once in the intro doc is helping for first-timers.
=> Explicitly state how to execute the web server

.github/CODEOWNERS
Adding this file should prompt Github to do this for every new PR, if I understand correctly.
=> All changes should be reviewed by twisted contributors.

src/klein/_decorators.py, src/klein/_form.py, src/klein/test/test_form.py, tox.ini
Enable `warn_unreachable` in `mypy`
=> Enable warn_unreachable in mypy

src/klein/__init__.py, src/klein/_app.py, src/klein/_form.py, src/klein/_resource.py, src/klein/test/test_app.py, src/klein/test/test_resource.py
Have less future, because the future is ~~scary~~ here.
=> Have less future

docs/examples/handlingerrors.rst, docs/examples/nonglobalstate.rst, src/klein/_app.py, src/klein/_dihttp.py, src/klein/_form.py, src/klein/_headers.py, src/klein/_headers_compat.py, src/klein/_message.py, src/klein/_plating.py, src/klein/_request.py, src/klein/_request_compat.py, src/klein/_requirer.py, src/klein/_resource.py, src/klein/_response.py, src/klein/_session.py, src/klein/_tubes.py, src/klein/resource.py, src/klein/storage/_memory.py, src/klein/test/test_app.py, src/klein/test/test_form.py, src/klein/test/test_plating.py, src/klein/test/test_resource.py, src/klein/test/test_session.py, src/klein/test/test_trial.py, src/klein/test/util.py
=> No need to explicitly inherit from object.

tox.ini
Minor cleanup of `tox.ini`, including a round of requirement updates that `requires.io` doesn't seem to notice.
=> Tox cleanup

src/klein/_app.py
Route and error handlers may be either functions or methods.
Use a `Union` to allow for signatures with and without the self argument.
=> Handle route and error handlers that are either functions or methods.

mypy.ini, src/klein/test/util.py
Add type hints to `klein.test.util` and remove the exception for it in `mypy.ini`.
=> Add type hints to klein.test.util.

mypy.ini, src/klein/_interfaces.py, src/klein/_plating.py, src/klein/_resource.py, src/klein/test/test_app.py, src/klein/test/test_resource.py
Enable `check_untyped_defs` in Mypy.
=> Enable check_untyped_defs

tox.ini
This is a major security problem for any local Klein development.
=> git:// URLs are not encrypted or authenticated

.github/workflows/cicd.yml
=> Use twisted/python-info-action

.github/workflows/cicd.yml, .readthedocs.yml, MANIFEST.in, setup.py, tox.ini
This tries to fix #459 
I saw that klein docs build were red in my RTD dashboard... so I tried to fix that
I failed as I have no idea how to fix the tox.ini ..
I am sending this PR, hoping that someone know how to fix it.
=> Add Read The Docs config.

mypy.ini, src/klein/_app.py, src/klein/_resource.py, src/klein/resource.py, src/klein/test/test_resource.py
Add type hints for `klein._resource`
=> Add type hints for klein._resource

.github/workflows/cicd.yml
Borrowing concept from https://github.com/twisted/twisted/pull/1548
=> Report python info for both system and tox pythons.

CONTRIBUTING.rst, docs/conf.py, tox.ini
This updates the code so that a PR will have all the checks greens.
I am targeting the PR checks, but I hope this is also fixing the `push` checks.
It fixed the pip deps resolution and updates some links that are permanently redirected.
=> Get the checks for a PR green.

src/klein/_resource.py
=> Avoid use of t.p.compat.intToBytes

setup.py, src/klein/_form.py
This has been deprecated for several years:
> DeprecationWarning: assoc is deprecated and will be removed after 2018/01.
=> Remove deprecated `attr.assoc()`

.flake8, .pre-commit-config.yaml, setup.py, src/klein/_requirer.py, src/klein/test/test_app.py
#581 has gotten stuck on these so I used `pur` to find the most recent versions manually.  Not sure if this will get the process unstuck
=> manually update dependencies that pre-commit seems to be having a hard time with
