twisted/klein

- AUTHORS
- CONTRIBUTING.rst
- docs/examples/subroutes.rst
- klein/app.py
- klein/test/test_app.py
- tox.ini
Adds a context manager that implements a concise syntax for taking advantage of Werkzeug's `routing.Submount` feature. A unit test and documentation for the new feature are provided, as well as a general documentation enhancement in cbceb6050.
> Add subroute feature

- klein/resource.py
- klein/test/test_resource.py
Make write_response check for NOT_DONE_YET because renderElement
finishes the request itself. Also updated test_requestWriteAfterFinish
to match new behavior.
This hopefully fixes issue #18 :)
> Switch from flattenString to renderElement.

- README.rst
I was looking at the maturity of the project to evaluate its use in [https://github.com/globaleaks/GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) as replacement for cyclone and i found strange that you were not exposing the code coverage badge given such the good results.
This coommit simply add codecov badge to README.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/twisted/klein/94)
> Add codecov badge to README.rst

- AUTHORS
- src/klein/__init__.py
- src/klein/resource.py
- src/klein/test/test_resource.py
Resolves #17 - Inside of Klein's resource.py, the `_extractURLparts` method tries to get the port number without checking to see if the connection is an AF_UNIX socket. This causes and exception because AF_UNIX sockets have no concept of a port number.
> Added logic to handle AF_UNIX sockets

- .travis.yml
- docs/introduction/1-gettingstarted.rst
- docs/introduction/codeexamples/html.py
- setup.py
- src/klein/__init__.py
- src/klein/_plating.py
- src/klein/plating.py
- src/klein/test/test_plating.py
- src/klein/test/test_resource.py
- tox.ini
> Plating Decorator

- src/klein/app.py
- src/klein/test/test_app.py
Updates app.Klein.run() so that user will be able to specify protocol (ssl, tcp, tcp6), certificate, private key and dh_parameters. This way it will be possible to easily run HTTPS site with Klein. It will also mean HTTP2 support for Klein will work ok with Twisted > 16.3.0. TLS is not formally required for HTTP2 but most client implementations require it.
cc @glyph @hawkowl
> Add support for SSL and TCP6 in app.Klein.run

- docs/examples/handlingerrors.rst
#110 wanted to see an example of a catch-all in the docs.  The docs are a bit sparse and more examples should be added.
> added example for "catch-all" routes

- README.rst
- setup.py
The updates released in 16.12 include a change that introduces dict comprehension that is Python 2.7+
This change updates the `setup.py` compatibility listing to suit, and adds a fancy badge to the README to show Python version coverage. (Note the badge shows what the pypi setup.py version includes, so it will only update when the changes are released)
> Update Python version compatibility listing

- src/klein/app.py
- src/klein/test/test_resource.py
Endpoint's `segment_count` attribute gets wrong value when route is created under `subroute()` context. Sub-apps or other routes with `branch=True` are failing to dispatch due to this.
Quick demo:
```python
class SubApp:
router = Klein()
@router.route('/hello')
def hello(self, request):
return b'hello world'
app = Klein()
with app.subroute('/sub'):
@app.route('/app', branch=True)
def sub_app(request):
return SubApp().router.resource()
```
Request to `/sub/app/hello` fails with 404 because sub-apps' router is getting `/app/hello` url for handling instead of `/hello`.
This PR is fixing this by increasing `endpoint.segment_count` inside `subroute()` context by the amount of segments in subroute prefix.
> Fixed usage of branch=True under subroute()

- src/klein/resource.py
- src/klein/test/test_resource.py
When `KleinResource` encounters Werkzeug's `HTTPException`, it takes response headers from `HTTPException.get_response({}).headers` and body from `HTTPException.get_body({})`. It is fine for most `HTTPException`s, but not for [`RequestRedirect`](https://github.com/pallets/werkzeug/blob/master/werkzeug/routing.py#L223) which overrides `get_response()` without overriding `get_body()`. This results with response whose body has different length than in `Content-Length` header.
This can be noticed when using `route(..., alias=True)` or when Werkzeug makes redirect to append trailing slash to the URL because `route()` was specified with trailing slash.
> Fix inconsistent Content-Length for redirect responses generated by Werkzeug

- docs/examples/handlingpost.rst
It took me a while to figure this out so I am adding it to the docs for future reference.
> new: doc: Show how to get the content of a request.

- .travis.yml
- src/klein/__init__.py
- src/klein/_decorators.py
- src/klein/_plating.py
- src/klein/_version.py
- src/klein/app.py
- src/klein/interfaces.py
- src/klein/resource.py
- src/klein/test/py3_test_resource.py
- src/klein/test/test_app.py
- src/klein/test/test_plating.py
- src/klein/test/test_resource.py
- src/klein/test/util.py
- tox.ini
This PR is for replacing our usage of `pyflakes` with `flake8` (which includes `pyflakes`), which will allow for more linting options long term, and since we can't easily make good use `twistedchecker` right now, it's a way to dial in some checks now.
> Use flake8

- .travis.yml
- setup.py
- tox.ini
We don't have much usage from Python 3.3:
I'd like to drop it from the support matrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/184)
> Remove Py3.3 support

- .travis.yml
- CONTRIBUTING.rst
- setup.py
- tox.ini
Drop support for `Twisted<15.5`.
PyPI data by Twisted version:
PyPI data by Twisted major version:
I sum up 356883 downloads.  59% use Twisted 17.  77% use Twisted>=16.  82% use Twisted >=15.
@glyph says if you use Twisted 14, you must suffer for it, so dropping that is a no-brainer, as we want to minimize suffering, or at least discourage it.
I'm going with a floor of 15.5 because (a) that's still two years ago, which I think is a good minimum, and (b) it's the first to support Python 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/185)
> Drop support for Twisted<15.5

- src/klein/app.py
- src/klein/resource.py
- src/klein/test/test_resource.py
Currently it is not permitted to return `Resource` instances from `Klein.handle_errors()` which seems inconsistent.
This PR replaces duplicated handling of `IRenderable` in `handle_errors` with calling the same `process()` in `KleinResource` as for returned value from non-error route functions.
> Allow returning Resource from handle_errors

- tox.ini
This prevents pip from hitting PyPI unnecessarily.
[Travis sets this by default now](https://github.com/travis-ci/travis-ci/issues/5499), so another way to do it is to pass it through, but this makes sense locally also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/191)
> Set PIP_DISABLE_PIP_VERSION_CHECK=1

- tox.ini
Remove twistedchecker-diff from default envlist, as it doesn't work outside of CI builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/193)
> Remove twistedchecker-diff from default envlist

- tox.ini
When invoking trial, add:
* `--random=0` to randomize tests
* `--logfile=X` to put logs in trial env tmp dri
* `--temp-directory=X` to put trial tmp dir in trial env tmp dir
The first helps find certain bugs in tests.
The latter two keep Tox runs from dropping turds in the source tree and drops them into the current environment's temporary directory instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/twisted/klein/194)
> trial invocation tweaks

- .coveragerc
It's not needed, and having Tox paths hard coded in there is odd.
> Remove [paths] section in .coveragerc

- tox.ini
`mock` and `coverage` are being included in all Tox environments, and are only required in some.
For example: `flake8` and `docs` do not need either.
Scope them into the environments where they are needed.
> Don't include mock and coverage when they aren't needed.

- .gitignore
Git ignore: use rooted paths for files that have a fixed location.
This is being a bit pedantic, but if there's a `.tox`, for example, in some other location, that's weird.
> Git ignore: use rooted paths for files that have a fixed location.

- src/klein/__init__.py
- src/klein/app.py
- src/klein/test/test_resource.py
Makes it possible to `from klein import handle_errors` just like `route`, `run` and `resource`. Useful for writing quick tests and examples.
> Allow "from klein import handle_errors"

- docs/examples/twistd.rst
Following @glyph comment about the need to add . back to sys.path when using twistd (for Twisted v. >= 17)
> Update doc twistd.rst #203

- docs/examples/await.rst
The markup at https://klein.readthedocs.io/en/latest/examples/await.html
doesn't look right.
> Fix markup

- requirements.txt
- src/klein/test/test_app.py
- src/klein/test/test_resource.py
The unit tests require mock but don't specify it, which causes
problems for any usages outside tox (e.g. testing that changes to
twisted don't break klein).  Use PEP508 to specify environment markers
and only install mock when required.  Tests can then conditionally
import unittest.mock and fall back to mock.
The conditional imports do raise a mypy error, discussed here:
https://github.com/python/mypy/issues/1153
So an annotation is required to silence this specific warning.
> Prefer unittest.mock but require mock for python < 3.3.

- src/klein/__init__.py
- src/klein/app.py
- src/klein/test/test_app.py
I'd like to propose `Klein.url_for()` method for reverse URL mapping.
```python
def url_for(self, request, endpoint, values = None, method = None, force_external = False, append_unknown = True)
```
`request` is the `Request` object. It is used to obtain correct hostname for external links. Other arguments are just like in Werkzeug's [`MapAdapter.build()`](http://werkzeug.pocoo.org/docs/0.11/routing/#werkzeug.routing.MapAdapter.build).
It can be used like this:
```python
from klein import route, run, url_for
@route('/user/<username>')
def user_page(request, username):
return "Welcome to {}'s homepage".format(username)
@route('/')
def homepage(request):
users = ['Alice', 'Bob', 'Carl']
return '<br/>'.join([
'<a href="{link}">{username}</a>'.format(
link=url_for(request, 'user_page', …
```
> Klein.url_for() for reverse URL mapping

- .gitignore
- src/klein/_headers.py
- src/klein/test/test_headers.py
- tox.ini
This PR does three things:
• In `tox.ini`, don't pin hypothesis now that [coverage tracking is fixed](https://github.com/HypothesisWorks/hypothesis-python/issues/997#event-1391243850).
• In `test_headers.py`, don't generate text only to filter out text that doesn't encode to Latin-1 when we can easily just generate Latin-1-encodable text.
• Remove `encodeValue`, which is unused and is therefore un-covered.
> Un-pin Hypothesis and fix performance issue in test_headers data generation.

- src/klein/_plating.py
- src/klein/test/test_plating.py
Widgets don't work with free functions that don't have a first positional argument, or with instance methods.
A first positional argument is required because the returned `wrapper` has `instance` as its first argument:
https://github.com/twisted/klein/blob/67580644a53201332ac48a0fa18769d19fad6338/src/klein/_plating.py#L167
Instance methods don't work because the `wrapper` can't forward the bound `self` to its invocation of `function`:
https://github.com/twisted/klein/blob/67580644a53201332ac48a0fa18769d19fad6338/src/klein/_plating.py#L168
because it's assigned as an attribute on the function:
https://github.com/twisted/klein/blob/67580644a53201332ac48a0fa18769d19fad6338/src/klein/_plating.py#L170
This PR introduces a descriptor that addresses both by binding the function it wraps on …
> Free widgets

- .travis.yml
- .travis/install
- .travis/run
- README.rst
- requirements.txt
- tox.ini
Things here:
* Add all dependencies into `tox.ini` with pinned versions, so that updates to dependencies (including flake8 and mypy) don't add unexpected curveballs into new PRs.
* Add Requires.io to `README.rst` so that we have an indicator when dependencies are outdated.
* Make it so that `skip_missing_intrepreters` is set to `False` for Travis builds, and that should be a failure mode there.  It's still defaults to `True`, as local dev test machines may not install every Python.
* Remove Twisted 15.5 from the test matrix, because it is now 17.12, and 17.12 - 15.5 = 2.7 (in base calendar), and that is > 2.
* Start using Travis CI's PyPy instead of installing it, now that Travis has a non-ancient PyPy (they have 5.8.0, which is newer than the 5.7.1 we've been installing).
* Add PyPy3 to …
> Pin all dependencies in tox.ini

- src/klein/_app.py
- src/klein/test/test_app.py
Instead, just tack a special-named attribute on the object to point to its
cached router.
- "has an instance dictionary" is a much less esoteric property than "is
hashable and comparable by identity"
- given the increased popularity of attrs, and its defaults, the hashability
requirement is a practical problem in a surprising number of circumstances
- Identity preservation of the Klein object is simply not always necessary, so
it's OK to just fail if it can't be met
> Remove hashability requirement for instances bound to Klein objects

- .travis/mypy
- src/klein/_message.py
- src/klein/_request.py
- src/klein/_response.py
- src/klein/_tubes.py
- src/klein/test/test_message.py
- src/klein/test/test_request.py
- src/klein/test/test_response.py
This adds:
* `_message.py`: A new `IHTTPMessage` interface and some functions for use by implementations.
* `_response.py`: A new `IHTTPResponse` interface, which is a superset of `IHTTPMessage` and `FrozenHTTPResponse` implementation.
* _request.py`: A new `IHTTPRequest ` interface, which is a superset of `IHTTPMessage` and `FrozenHTTPRequest ` implementation.
* `_tubes.py`: Implements to code that allows converting `bytes` to a fount and back, and an `IOFount` class that wraps an FLO as a fount.  This code should eventually live in Tubes.  Note that the implementation of `IOFount` is not optimal, as it doesn't stream IO.  That can be done later; the point here is to establish an API for streaming in `IHTTPMessage`.
> Add new request and response API

- .travis/mypy
- src/klein/_headers_compat.py
- src/klein/test/test_headers_compat.py
This class wraps `twisted.web.http_headers.Headers` object and exposes it as an `IHTTPHeaders` implementation.
> Add HTTPHeadersWrappingHeaders

- setup.py
- src/klein/_plating.py
- src/klein/test/test_plating.py
- src/klein/test/test_resource.py
Plating is good but it has ~~two problems~~ a problem with JSON. (See below for strikethrough)
Consider the following program:
```python
from klein import Klein, Plating
from twisted.internet import task, reactor
from twisted.web.template import tags, slot
app = Klein()
style = Plating(tags=tags.html(slot(Plating.CONTENT)))
@style.routed(
app.route("/"),
tags.div(
tags.div(slot("immediate")),
tags.div(slot("delayed")),
)
)
def route(request):
return {
"immediate": "now",
"delayed": task.deferLater(reactor, 1, lambda: "later")
}
app.run("localhost", 8081)
```
The power of `twisted.web.template` and browsers (or at least Firefox) combine to render "now" a second before "later" appears.  Requesting the same page with `?json=1` fails with a [`TypeError: <Deferred at 0xabcdef> not JSON …
> Concurrent JSON

- CONTRIBUTING.rst
This makes it so `detox` runs cleanly for me locally, which is nice.
> fix sphinx link for docs-linkcheck

- src/klein/__init__.py
- src/klein/resource.py
- src/klein/test/test_exports.py
- src/klein/test/test_resource.py
Fixes #224 
Supersedes #225 
I think we should probably eventually deprecate `klein.resource.KleinResource` as the public name and expose it somewhere else, but for the time being, let's resolve things in as friendly a way as possible, so that everything keeps working regardless of what order you import things in.
> resolve weird klein.resource namespace conflict, gently as possible

- src/klein/_app.py
- src/klein/test/test_app.py
Some properties might raise AttributeError even though they are
otherwise visible, we can safely ignore them because Klein will
not do this.
Fixes #257
> Ignore AttributeError when searching for Klein instance.

- .coveragerc
- src/klein/__init__.py
- src/klein/_interfaces.py
- src/klein/_typing.py
- src/klein/resource.py
At @glyph suggestion, use `coverage`'s config to exclude `TYPE_CHECKING` branches from coverage instead of pragmas.
> Use config to exclude TYPE_CHECKING branches from coverage

- docs/introduction/1-gettingstarted.rst
Hi!
I was a bit confused by the documentation here, turns out the literalinclude had the wrong line offset. :)
I think this should correct the discrepancy between html.py and 1-gettingstarted.rst
> Correct two off by one errors in line numeration

- .travis.yml
- tox.ini
Stop testing 3.4 against twisted trunk, both in local tox and in Travis.
> twisted trunk has dropped python 3.4 support

- src/klein/test/test_headers.py
The trunk builds have been failing for a while due to overzealous hypothesis value generation; this fixes it.
> Account for new header-splitting attack protection in Twisted.

- .travis.yml
PyPy 7 is now available on Travis CI via `pypy` and `pypy3`, which have the PyPy2.7 and PyPy3.6-beta interpreters.
This would unblock dropping Python 3.5, if required, eg. https://github.com/twisted/klein/issues/279:
> Anything Python 3 less than 3.6 is weak salsa
And Python 3.5 download numbers are quite low. Here's the pip installs for klein from PyPI for May 2019:
| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  47.51% |    17,587 |
|      2.7 |  35.11% |    12,998 |
|      3.7 |  12.00% |     4,443 |
|      3.5 |   4.16% |     1,539 |
| null     |   1.00% |       371 |
|      2.6 |   0.10% |        38 |
|      3.4 |   0.10% |        37 |
|      3.8 |   0.02% |         6 |
| Total    |         |    37,019 |
Source: `pypistats python_minor klein …
> Upgrade to PyPy 7

- tox.ini
This should address the failing build on `master` right now.
> pin pydocstyle to version compatible with flake8-docstrings

- tox.ini
In the `black` Tox environment, `black` is running such that it reformats the code, when it should only be checking the code.  This PR fixes that.
Now we get the correct error with a formatting oopsie, rather than actually fixing the code for you:
```console
$ tox -e black
black installed: appdirs==1.4.3,attrs==19.3.0,black==19.10b0,Click==7.0,pathspec==0.7.0,regex==2020.1.8,toml==0.10.0,typed-ast==1.4.1
black run-test-pre: PYTHONHASHSEED='3269586295'
black run-test: commands[0] | black --check src
would reformat /Users/wsanchez/Dropbox/Developer/Twisted/klein/src/klein/_app.py
Oh no! 💥 💔 💥
1 file would be reformatted, 48 files would be left unchanged.
ERROR: InvocationError for command /Users/wsanchez/Dropbox/Developer/Twisted/klein/.tox/black/bin/black --check src (exited with code 1) …
```
> Set BLACK_LINT_ARGS in Tox black environment

- src/klein/_app.py
- src/klein/_imessage.py
While there are quite a few problems left in the pydoctor output, this does cover all the epytext errors.
> Fix docstring markup problems reported by pydoctor

- .travis.yml
- tox.ini
This removes the (fail-able) build with Twisted trunk on Python 2.7, which now always fails, and replaces Twisted 17.1.0 with 19.2.1 in the matrix, per the 2-year compatibility window.
> Update build matrix

- .travis.yml
- NEWS.rst
- docs/release.rst
- release.py
- setup.py
- src/klein/_version.py
- tox.ini
This is PR #329 with a new name
> Release 20.6

- src/klein/test/test_app.py
- src/klein/test/test_resource.py
- tox.ini
Remove py2-specific `mock`, `typing` import handling.
> Remove py2-specific mock, typing import handling.

- .travis.yml
This splits the CI jobs into [three stages](https://travis-ci.org/github/twisted/klein/builds/709526045):
* Lint and Code Style
* Tests (Python 3.8)
* Tests
The purpose of this is to reduce workload on Travis CI in typical cases where the build fails. It does this by first running the cheaper tests (flake8, mypy, black, packaging).  If any of those fail, it stops there.  Otherwise, it runs the Python 3.8 tests, and then if those pass, it runs the rest of the jobs.
This should abort more quickly in most failure cases, and that in turn should avoid a CI run from waiting for jobs in a prior run that already has a failed job.
> Add build stages to Travis config

- setup.py
- src/klein/py.typed
Add a `py.typed` file to the `klein` package.
Fixes #294
After #359, we have plenty of useful type hints for clients in the more commonly used parts of Klein.
> Export type hints

- release.py
- tox.ini
Enable `warn_return_any` for `mypy`.
> Enable warn_return_any

- docs/examples/staticfiles.rst
Update the static files example with sample code that disables directory listings. This is important in production environments where users should not expose more information than necessary.
Fixes: #277
> docs: explain how to disable directory listings

- src/klein/test/_strategies.py
[Builds against twisted trunk are failing in CI](https://travis-ci.org/github/twisted/klein/jobs/714554533) because `twisted.python.compat._PY3` went away.
I don't know if this means that we need to get a release out the door before Twisted ships with that change, because the effected file is `_strategies.py`, which is private testing… but it does mean that running Klein's tests after an install will fail.
> Don't use _PY3

- src/klein/test/_strategies.py
This isn't needed any more since klein dropped support for Python 2.
> Don't use twisted.python.compat.unicode

- src/klein/__init__.py
- src/klein/_app.py
- src/klein/_form.py
- src/klein/_headers.py
- src/klein/_headers_compat.py
- src/klein/_plating.py
- src/klein/_request_compat.py
- src/klein/_resource.py
- src/klein/test/_trial.py
- src/klein/test/test_app.py
- src/klein/test/test_form.py
- src/klein/test/test_headers.py
- src/klein/test/test_message.py
- src/klein/test/test_plating.py
- src/klein/test/test_resource.py
Replace `"{}".format()` with `f"{}"`.
This is both more concise and, word has it, faster.
Subset of #384.
> Use f-strings

- .github/workflows/cicd.yml
- tox.ini
Looking at the huge test matrix on #401 and the number of times github actions CI has failed, apparently due to a timeout, I thought it might be nice to just drop some more irrelevant stuff.
I'd also love to raise our minimum supported Python version at some point, but that seems like it might be a bigger deal and interact with more things like distro-supplied interpreter versions.
> raise minimum supported version of Twisted to 19.2 and prune tox

- src/klein/_app.py
Query values may be int or float, not just str.
> Expand types for query values.

- setup.py
`typing_extensions` is only needed for Python < 3.8
> Don't bring in typing_extensions for Python 3.8+

- src/klein/_app.py
Fix type hint for `Klein._error_handlers`.
The correct type is a list of 2-tuples, where the first element is a list of exception types to handle, and the second element is the handler for that list of exception types.
You can see where we add such a tuple to the list to `Klein._error_handlers` [here](https://github.com/twisted/klein/blob/9d81819cd9db5728ce9f7e477f62945806347563/src/klein/_app.py#L497).
> Fix type hint for Klein._error_handlers.

- mypy.ini
Turn on `strict_equality` in Mypy.
No code changes required; we already comply.
> Turn on strict_equality in Mypy.

- src/klein/_app.py
The first argument to `urlFor` is an `IRequest`, not an `IKleinRequest`.
To confirm this, note that the [tests are passing in the result of calling `requestMock()`](https://github.com/twisted/klein/blob/f34a62f4db173aba6ec4ed0106a43898a7af8d25/src/klein/test/test_app.py#L532) and that [`requestMock`](https://github.com/twisted/klein/blob/f34a62f4db173aba6ec4ed0106a43898a7af8d25/src/klein/test/test_resource.py#L32) builds a `twisted.web.server.Request` up and returns it, and `twisted.web.server.Request` is an `IRequest`, not an `IKleinRequest`.
> The first argument to urlFor is an IRequest.

- src/klein/test/test_request_compat.py
- src/klein/test/test_resource.py
Add (incomplete) type hints to `klein.test.test_resource`.
This isn't enough to remove the exception in `mypy.ini`, but it's a start.
> Add (incomplete) type hints to klein.test.test_resource.

- mypy.ini
- src/klein/_app.py
Add type hints for `handle_errors`.
This rounds out the type hints for `klein._app`.
This one was a bit tricky, and took me a few tries, but was nicely covered by using `@overload`.
> Add type hints for handle_errors.

- tox.ini
This fixes CI failures where the latest Twisted version (21.2.0) broke our mypy runs.
Will look at fixing that in a separate PR, but this is blocking all other PRs.
> Pin Twisted for mypy

- mypy.ini
Turn off `allow_untyped_defs` for `klein.test._trial`.
> Turn off allow_untyped_defs for klein.test._trial

- tox.ini
This adds some indirect dependencies that were not pinned in Tox before.
> Fill in pinned dependencies in Tox config.

- mypy.ini
Hyperlink ships with type hints now, so we can stop ignoring missing type hints for it
> Hyperlink ships with type hints now

- .coveragerc
- tox.ini
This is to address the giant (60%) coverage drop after we added the `--jobs=2` argument to `trial`.
> Create pth file to start coverage in subprocesses

- tox.ini
`--ignore-errors` was added when building coverage XML due to `async`/`await` syntax confusing older python versions.
I think it may no longer be necessary.
> Remove --ignore-errors when building coverage XML.

- README.rst
- docs/examples/handlingpost.rst
- docs/index.rst
This fixes a dead link that I noticed while looking at #478, updates a PyPI link, and removes a living-dead link to Travis.
I also ported one of the examples to Python 3 since I noticed it was using the wrong types in `request.args` while fixing an adjacent link.
> Fix links, port POST example to Python 3

- .github/workflows/cicd.yml
- tox.ini
To speed up the tests we can run pypy tests without coverage.
I have checked the source code and I don't see any specific pypy handling in klein.
The coverage run on pypy is slow as there is no extension to speed the run.
Don't run coverage on pypy.
Move coverage combine and XML generation into tox.ini ... we already had combine... but no xml generate.
XML generate in tox can help with a future usage of local `diff_cover`
See for example a run with coverage enabled on pypy
With faster pypy and no coverage changes or decrease in coverage
> Don't run coverage on pypy.

- src/klein/_decorators.py
- src/klein/_form.py
- src/klein/_session.py
- src/klein/test/test_form.py
There are small typos in:
- src/klein/_decorators.py
- src/klein/_form.py
- src/klein/_session.py
- src/klein/test/test_form.py
Fixes:
- Should read `unconditionally` rather than `unconditinally`.
- Should read `iterable` rather than `interable`.
- Should read `dependency` rather than `dependnecy`.
- Should read `attempts` rather than `attempst`.
Closes #494
> docs: fix a few simple typos

- src/klein/_app.py
- src/klein/test/test_resource.py
- tox.ini
* A redundant space before the word "If" is remove in Werkzeug 2.0
https://github.com/pallets/werkzeug/commit/5fd13860d7f649fbe592601b1dea728050daffa5#diff-b9d6906a0da8b5a9877b17ac5ea491161a660ce7e513921738d3e284bd9e9c96L528
* A `cast()` is no longer needed as Werkzeug 2.x is properly
type-annotated: https://github.com/pallets/werkzeug/commit/967b2dabed79c4a999cfb0e6d5bf01437b246dee
I noticed this when I was testing klein with the latest Python packages. Someone Werkzeug is not automatically upgraded via requires.io, and several others (e.g., attrs, six) are already out-dated before the last requires.io pull request (https://github.com/twisted/klein/pull/498), too. I guess something was wrong at their end.
> Upgrade Werkzeug to 2.x and fix affected tests

- .pre-commit-config.yaml
- src/klein/_app.py
- src/klein/_dihttp.py
- src/klein/_form.py
- src/klein/_headers_compat.py
- src/klein/_iform.py
- src/klein/_imessage.py
- src/klein/_isession.py
- src/klein/_message.py
- src/klein/_plating.py
- src/klein/_request.py
- src/klein/_request_compat.py
- src/klein/_requirer.py
- src/klein/_resource.py
- src/klein/_response.py
- src/klein/_session.py
- src/klein/_tubes.py
- src/klein/test/test_app.py
- src/klein/test/test_form.py
- src/klein/test/test_headers_compat.py
- src/klein/test/test_message.py
- src/klein/test/test_plating.py
- src/klein/test/test_request_compat.py
- src/klein/test/test_requirer.py
- src/klein/test/test_resource.py
- src/klein/test/test_session.py
- src/klein/test/util.py
- tox.ini
Un-pin Twisted when running Mypy.
It's pinned right now because with Twisted 21, we have numerous new errors.
> Run mypy with current Twisted

- .isort.cfg
- NEWS.rst
- release.py
- setup.py
- src/klein/_version.py
- src/klein/py.typed
- tox.ini
This release excludes `py.typed`, as type hints aren't fully baked
> Release 21.8

- setup.py
- src/klein/py.typed
This reverts commit 3149dc985ca09418c86beccd618c881e6decc246.
> Revert "Don't install py.typed"

- .pre-commit-config.yaml
`no-commit-to-branch` is causing the CI merge to master to fail which I guess it's supposed to… comment it out until someone has a clue how to disable it in CI only.
> Disable no-commit-to-branch

- tox.ini
the bug in question: https://github.com/twisted/twisted/issues/11580
fixes #486
the `--logfile` option is intended to be a *relative* path from the temp dir
anyway, so even after this bug is fixed we should not put this back; I have no
idea how we ended up with this in the first place.
> workaround for `trial -j` bug with log paths

- .github/workflows/cicd.yml
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- docs/conf.py
- docs/examples/alternativerunning.rst
- docs/examples/disablingtracebacks.rst
- docs/examples/twistd.rst
- src/klein/_resource.py
Fixes #572
Try to get the CI workflow green
Changes
-------
* Update isort in pre-commit
* Pin tox to pre v4
* Fix links in docs
* Update GitHub action branch protection to only require "klein-required". In this way, we can control branch protection from the source code, without having to go to https://github.com/twisted/klein/settings/branch_protection_rules/512098 to update the rules
> [#572] Get the GitHub Action CI green.

- .gitignore
- mypy.ini
- requirements/tox-tests.txt
- src/klein/test/__init__.py
- src/klein/test/not_hypothesis.py
- src/klein/test/test_headers.py
- src/klein/test/test_message.py
- src/klein/test/test_plating.py
- src/klein/test/test_request_compat.py
- tox.ini
Fixes #561
I am not entirely convinced we need Hypothesis at all, but if we do, when we reintroduce it we have to *first* do the work to make it deterministic in CI and to address the various deficiencies in Hyperlink's strategies if we want to use those.
> remove hypothesis (at least for now)
